services:
  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: MobilityParkData
      PGUSER: postgres
    logging:
      options:
        max-size: 10m
        max-file: 3
    ports:
      - "5434:5432"
    expose:
      - "5434"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-data:
